In [1]:
import paths
import config

import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

In [8]:
data_prefix = "../data/"
train_data = data_prefix+"train.npy"
train_labels = data_prefix+"train_labels.npy"
valid_data = data_prefix+"dev.npy"
valid_labels = data_prefix+"dev_labels.npy"
test_data = data_prefix+"test.npy"
test_labels = data_prefix+"test_labels.npy"

model = "../model/model_dict.pt"

In [23]:
mode = 'train'
paths.train_data = train_data
paths.train_labels = train_labels
if mode == "train":
    data_path = paths.train_data
    labels_path = paths.train_labels
    shuffle = True
if mode == "val":
    data_path = paths.valid_data
    labels_path = paths.valid_labels
    shuffle = False
if mode == "test":
    data_path = paths.test_data
    labels_path = None
    shuffle = False
data = np.load(data_path)
if config.sanity:
    data = data[:150]

#padding the data


In [24]:
print (len(data), len(data[0]), len(data[0][0]))
print (type(data), type(data[0]), type(data[0][0]), type(data[0][0][0]))


150 477 40
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.float32'>


In [30]:
if labels_path:
    labels = np.load(labels_path)
    if config.sanity:
        labels = labels[:150]

    print(data.shape, labels.shape, type(data), type(labels), )
    tmp = np.zeros(3 * 3 * 3 ).reshape((3, 3, 3))
    print (tmp.shape)
    print (type(tmp))
    tmp = torch.from_numpy(tmp).type(torch.float32)
    labels = torch.from_numpy(labels).type(torch.LongTensor)
print (len(data))


(150,) (150,) <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(3, 3, 3)
<class 'numpy.ndarray'>


TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

In [38]:
a = np.zeros((9, 9))
print (a)
print (np.pad(a, ((2, 3), (1, 1)), 'constant', constant_values=1))
a = a.reshape(-1)
print (a.reshape(-1))
a = np.array(a)
print (a)
a = np.array(a)
print (len(a))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0

In [1]:
import data
import mlpmodel
import routine
import config
import numpy as np

In [2]:
print (config.hidden_size)

1024


In [3]:
train_loader = data.get_loader("train")
val_loader = data.get_loader("val")
test_loader = data.get_loader("test")

FileNotFoundError: [Errno 2] No such file or directory: '../data/train.npy'

In [4]:
if config.load_model:
    model = mlpmodel.MLP.load()
else:
    model = mlpmodel.MLP(config.input_size, config.hidden_size, config.output_size, config.CUDA)


torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])
torch.Size([32, 1000]) torch.Size([32])


In [5]:
routine.train(model, train_loader, val_loader)

begin training
Epoch 1
Training loss : 4.044030608802006
Validation loss : 4.6022375002503395
Epoch 2
Training loss : 3.4429340280335525
Validation loss : 4.601064162121879
Epoch 3
Training loss : 3.387573061318233
Validation loss : 4.53630162941085
Epoch 4
Training loss : 3.24060609422881
Validation loss : 4.5351868371168775
Epoch 5
Training loss : 3.10230723742781
Validation loss : 4.462813617454635
Epoch 6
Training loss : 3.055833438347126
Validation loss : 4.6428190271059675
Epoch 7
Training loss : 3.038285197882817
Validation loss : 4.990308544702
Epoch 8
Training loss : 3.035525050656549
Validation loss : 5.07477699385749
Early stopping !


In [7]:
test_outputs = routine.predict(model, test_loader)

In [14]:
print((test_outputs))

[108 108 108 108 108 108 108 108 108 110 110 110  11  11  11  11  18  18
  18  18  18  18  18  18  27  27  28  28  28  28  28  28  28  28  28  28
  28  28  34  34  34  52  52  52  35  35 102 102 102 102  75  75  82  82
  82  82  89  80 104  51  51  67 102  68 124  58  58  18  18  18  18  27
  51  51  28  28  28  28  52  52  52  52  35  35 102 102 102 102  75  75
  75 133 133  83  83  24  24  24  51  26 102  68 124  79  58  18 120 127
  34  52  52  52  52  52  25  23  53 102  75  75  75 133 125 125 125 125
  77 104 104 104 104 111  85 112 112  18  18  18  27  27  27  27  28 120
 120  28  52  52  52  52  52  53  53  53  53  75  75  75   5 125 125   5
   5 111 111 104 104  66  66  18  67  68  68  68 104  18  18  18  18  18
  51  51  28  28  28  28  28  28  28  28  52  52  52  52  35 102 102  81
  81  75  82  82 125 125 125  24  51  51 101  26 102  81  58  58  58  58
  58 104 126 127 127  24  52  52  52  52  52  26  26 102  81  75  75  82
 103 103 103  83  83  51  51  51  25  52  52  52  2

In [20]:
import csv
def writecsv(file,filename,flag=3):
    csvfile = open(filename, 'w')
    writer = csv.writer(csvfile,lineterminator='\n')
    #0 nodes , 1 = edgees
    for i, line in enumerate(file):
        writer.writerow((i,line))
    csvfile.close()

In [21]:
writecsv(test_outputs, 'prediction.csv')

In [15]:
try:
    np.savetxt('prediction.csv', test_outputs, delimiter=",")
except:
    print("prediction not saved")